  name: Claude
  on: push
  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: anthropics/claude-code-action@beta
          with:
            anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
