  name: Claude
  on:
    issue_comment:
      types: [created]
  jobs:
    claude:
      if: github.event.issue.pull_request == null
      runs-on: ubuntu-latest
      steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.CLAUDE_GITHUB_TOKEN }}
