  name: Claude
  on: [push, issue_comment]
  jobs:
    test:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        issues: write
        pull-requests: write
      steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
